# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: springboot-mongo

on:
  push:
    branches: [ dct ]
  pull_request:
    branches: [ dct ]

jobs:
  Container_Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3.4.1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean  package --file pom.xml
    - name: docker build
      run: |
        docker build -f $GITHUB_WORKSPACE/Dockerfile -t funacr.azurecr.io/spring:${{ github.run_number }} .
    - name: acr login
      run: |
        az acr login  -n funacr.azurecr.io --username funacr --password PbrhYU36JgUQl6EMYGfdvrxp3s=NES1e
    - name: docker push 
      run: |
        docker push funacr.azurecr.io/spring:${{ github.run_number }}
  AKS_deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: Container_Build
    steps:
    - name: Checkout
      uses: actions/checkout@v2   
    
    - name: Azure Login
      uses: Azure/login@v1
      with:
         # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{ secrets.AZURE_CREDENTIALS }}
  
    - name: Azure Kubernetes set context
      uses: Azure/aks-set-context@v2.0
      with:
        # Azure credentials i.e. output of `az ad sp create-for-rbac --sdk-auth`
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        # Resource Group Name
        resource-group: funrg
        # AKS Cluster Name
        cluster-name: funAKS
     
    - uses: azure/k8s-create-secret@v2.1
      name: Create imagepullsecret for ACR
      with:
        container-registry-url: ${{ secrets.REGISTRY_NAME }}.azurecr.io
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        secret-name: ${{ secrets.REGISTRY_NAME }}-registry-connection
    
        
    - name: Deploy to Kubernetes cluster
      uses: Azure/k8s-deploy@v3.0
      with:       
        manifests: springBootMongo.yml      
        images: funacr.azurecr.io/spring:${{ github.run_number }}
        imagepullsecrets: |
          ${{ secrets.REGISTRY_NAME }}-registry-connection
        force: true
