# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ dct ]
  pull_request:
    branches: [ dct ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: docker build
      run: |
        docker build -t funacr.azurecr.io/spring:${{ github.run_number }} .
        az acr login  -n funacr.azurecr.io --username funacr --password PbrhYU36JgUQl6EMYGfdvrxp3s=NES1e
        docker push funacr.azurecr.io/spring:${{ github.run_number }}
    - name: Azure Login
      uses: Azure/login@v1
      with:
         # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure Kubernetes set context
      uses: Azure/aks-set-context@v1
      with:
        # Azure credentials i.e. output of `az ad sp create-for-rbac --sdk-auth`
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        # Resource Group Name
        resource-group: funrg
        # AKS Cluster Name
        cluster-name: funAKS
    - name: Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        # comma separated list of XML/JSON/YAML files in which tokens are to be substituted. Files names must be specified relative to the folder-path.
        files: springBootMongo.yml
    - name: Deploy to Kubernetes cluster
      uses: Azure/k8s-deploy@v1.3
      with:
        # Path to the manifest files which will be used for deployment.
        manifests: springBootMongo.yml
         # Fully qualified resource URL of the image(s) to be used for substitutions on the manifest files Example: contosodemo.azurecr.io/helloworld:test
        images: funacr.azurecr.io/spring:${{ github.run_number }}
        force: true
